config/routes.rb
Wkpool::Application.routes.draw do
  scope '/app' do
    get 'users/welcome' => 'users#welcome', :as => 'welcome'
    get 'pools/:id/invite' => 'pools#invite', :as => 'invite_pool'
    post 'create_multiple_predictions', to: 'predictions#create_multiple_predictions'
    patch 'update_multiple_predictions', to: 'predictions#update_multiple_predictions'
    get 'pouleeindstanden/:id' => 'predictions#pouleeindstanden', :as => 'pouleeindstanden'
    get 'knockoutfase/:id' => 'predictions#knockoutfase', :as => 'knockoutfase'
    get 'bonusvragen/:id' => 'predictions#bonusvragen', :as => 'bonusvragen'
    resources :pools, :users, :predictions, :teampredictions, :poolmemberships, :knockoutpredictions, :quarterpredictions, :semipredictions, :finalpredictions
    post 'create_multiple_predictions', to: 'predictions#create_multiple_predictions'
    get 'givepoints' => 'predictions#givepoints', :as => 'givepoints'
    post 'create_multiple_teampredictions', to: 'teampredictions#create_multiple_teampredictions'
    patch 'update_multiple_teampredictions', to: 'teampredictions#update_multiple_teampredictions'
    get 'givepoints2' => 'predictions#givepoints2', :as => 'givepoints2'
    get 'bier' => 'predictions#bier', :as => 'bier'
    get 'pointsscript' => 'predictions#pointsscript', :as => 'pointsscript'
    get 'pointsscript2' => 'predictions#pointsscript2', :as => 'pointsscript2'
    get 'speluitleg' => 'pages#speluitleg', :as => 'speluitleg'
    get 'ranking' => 'poolmemberships#ranking', :as => 'ranking'
    resources :games do
      member do
        patch :toggle
      end
    end
    resources :teams do
      member do
        patch :toggle
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  get 'logout' => 'sessions#destroy', :as => 'log_out'
  get 'login' => 'sessions#new', :as => 'log_in'
  get 'register' => 'users#new', :as => 'register'

  get 'app' => 'users#dashboard', :as => 'app_root'

  root  'pages#home'

  get 'ping' => proc { |env| [200, {}, ['pong']] }
  get "/500", :to => "errors#error_500"
  get "/404", :to => "errors#error_404"

end

app/models/pool.rb
class Pool < ActiveRecord::Base
  has_secure_password validations: false
  has_many :poolmemberships, dependent: :destroy
  has_many :users, through: :poolmemberships

  before_save :clear_passwords, if: :public_pool?

  # Memberships (image breaker)
  validates_inclusion_of :maximum_membership, :in => 5..65
  validate :value_is_multiple_of_five

  # Name
  validates :name,
            length: {
              minimum: 3,
              maximum: 35,
              message: '* De poolnaam moet tussen 3-35 karakters hebben.'
            },
            uniqueness: {
              message: '* Deze poolnaam is al bezet.'
            },
            format: {
              with: /\A(([a-zA-Z0-9]+[-_'\s]{0,1})+)\z/,
              message: 'Het is niet toegestaan meerdere spaties, "-", "_" of "\" achter elkaar te
                        plaatsen.'
            }

  # Password
  validates :password,
            if: :private_pool?,
            presence: false,
            allow_blank: false,
            length: {
              minimum: 5,
              message: '* Het wachtwoord moet minimaal 5 karakters zijn.'
            },
            confirmation: {
              message: '* De wachtwoorden komen niet overeen.'
            }

  # Avatar
  has_attached_file :avatar,
                    styles: {
                      medium: '500x500>',
                      small: '265x265>',
                      thumb: '100x100#',
                      mini: '70x50#'
                    },
                    default_url: 'pool/:style/missing.png'

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  before_post_process :check_file_size

  # Methods
  def public_pool?
    is_public == true
  end

  def private_pool?
    is_public == false
  end

  def clear_passwords
    self.password_digest = ''
  end

  def check_file_size
    valid?
    errors[:avatar_file_size].blank?
  end

  def value_is_multiple_of_five
    unless maximum_membership % 5 == 0
      errors.add(:maximum_membership, 'must be multiple of 5')
    end
  end

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    # where("name like ?", "%#{query}%")
    t = self.arel_table
    where(t[:name].matches("%#{query}%"))
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  require 'will_paginate/array'
  skip_before_filter :ensure_user, :only => [:show]

  def index
    @openpool = params[:openpool] || '0'
    @poolspace = params[:poolspace] || '1'
    @poolsearch = params[:search]
    @playerssearch1 = params[:playerssearch1] || '5'
    @playerssearch2 = params[:playerssearch2] || '65'

    @pools = Pool.where(
      maximum_membership: (@playerssearch1..@playerssearch2)
    )

    if @openpool != '0'
      @pools = @pools.where(is_public: @openpool == '1' ? true : false)
    end

    if @poolspace == '2'
      @pools = @pools.where("maximum_membership > poolmemberships_count")
    end

    if !@poolsearch.nil?
      @pools = Pool.search(params[:search])
    end

    @pools = @pools.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    if current_user.poolmemberships.count == 5
      flash[:error] = 'Je zit al in 5 pools.'
      redirect_to :back
    else
      @pool = Pool.new
    end
  end

  def edit
    @pool = Pool.find(params[:id])
    @my_pool = @pool.users.where(id: current_user.id).count > 0 ? true : false
    @poolmember = @pool.poolmemberships.where(user_id: current_user.id).first
  end

  def create
    @pool = Pool.new(pool_params)
    if current_user.poolmemberships.count == 5
      flash[:error] = 'Je zit al in 5 pools.'
      redirect_to :back
    else
      if @pool.save
        @pool.poolmemberships.create(user: current_user, role: 1)
        render 'confirmation'
      else
        render 'new'
      end
    end
  end

  def show
    @pool = Pool.find(params[:id])
    if current_user.present?
      @my_pool = @pool.users.where(id: current_user.id).count > 0 ? true : false
      @poolmember = @pool.poolmemberships.where(user_id: current_user.id).first
    else
    end
    
  end

  def update
  @pool = Pool.find(params[:id])
  @poolmember = @pool.poolmemberships.where(user_id: current_user.id).first
    if @poolmember.role == 1
      if @pool.update_attributes(pool_params)
        redirect_to pool_path(@pool.id)
        flash[:success] = "Succes! '#{@pool.name}' is aangepast!"
      else
        redirect_to pool_path(@pool.id)
        flash[:error] = "Er is iets verkeerd gegaan bij het aanpassen van '#{@pool.name}'."
      end
    else
      redirect_to pool_path(@pool.id)
      flash[:error] = "Je hebt geen toestemming om '#{@pool.name}' aan te passen."
    end
  end

  def destroy
    @pool = Pool.find(params[:id])
    @pool.destroy
    flash[:success] = 'Pool verwijderd.'
    redirect_to pools_path    
  end

  def invite
    @pool = Pool.find(params[:id])
  end

  private

  def pool_params
    params.require(:pool).permit(:name, :image, :is_public, :password,
                                 :password_confirmation,
                                 :maximum_membership, :avatar, :score1, :prediction1)
  end
end

app/views/pools/confirmation.html.erb
<% title "Pool overzicht" %>
<div class="grid-r">
  <div class="medium-3-4">
    <div class="box">
      <div class="pool-step">
        <div class="steps">
          <div class="step active">
            1. <span class="default-hide small-show">Pool informatie</span>
          </div>
          <div class="step active">
            2. <span class="default-hide small-show">Bevestigen</span>
          </div>
          <div class="step">
            3. <span class="default-hide small-show">Vrienden uitnodigen</span>
          </div>
        </div>
      </div>

      <div class="content-header">
        <h1>2. Pool gegevens</h1>
      </div>

      <div class="grid-r">
        <div class="small-1-3">
          <div class="avatar">
            <%= image_tag @pool.avatar.url(:small), id: 'uploadPreview' %>
          </div>
        </div>
        <div class="small-2-3">
          <div class="pool_new_form">
              <div class="form-field">
              <%= label :name, 'Pool naam' %>
              <h3><%= @pool.name %></h3>
            </div>

            <div class="form-field">
              <%= label :maximum_membership, 'Maximaal aantal spelers' %>
              <h3><%= @pool.maximum_membership %></h3>
            </div>

            <div class="form-field inline">
              <label>Toegankelijkheid</label>
              <% if @pool.is_public? %>
                <h3>Openbare pool</h3>
              <% else %>
                <h3>Priv&eacute; pool</h3>
              <% end %>
            </div>

            <% if !@pool.is_public? %>
            <div class="form-field" id="private_pool_enabled">
              <div class="form-field">
                <label for="poolnaam">Wachtwoord</label>
                <h3>
                  <span class='password'><% @pool.password.length.times do %>*<% end %></span>
                  <span class='hide password'><%= @pool.password %></span>
                </h3>
                <h3>
                  <a class="togglepassword" href="#">Toon wachtwoord</a>
                  <a class="togglepassword hide" href="#">Verberg wachtwoord</a>
                </h3>
              </div>
            </div>
            <% end %>

            <div class="form-field">
              <%= link_to invite_pool_path(@pool.id), :class => 'green btn left' do %>
                Volgende stap &nbsp; <%= fa_icon 'chevron-right' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class='default-0 medium-1-4'>
    <%= render "shared/aside" %>
    <%= render "shared/aside_ad" %>
  </div>
</div>

<%= javascript_tag do %>
  poolPassword();
<% end %>

app/views/pools/edit.html.erb
<% title "#{@pool.name} aanpassen" %>
<% if @poolmember.role == 1 %>
<div class="grid-r">
  <div class="medium-3-4">
    <div class="box">
      <%= form_for @pool, :url => { :action => "update" } do |f| %>
        <div class="content-header">
          <h1>Pool aanpassen</h1>
        </div>

        <div class="content-header">
          <span class="default-hide small-show">
            <a href="../<%= @pool.id %>" class="btn grey left"><i class="fa fa-chevron-left"></i> Terug naar <%= @pool.name%></a>
          </span>
          <%= link_to 'Pool verwijderen', @pool, method: :delete, data: { confirm: 'Weet je zeker dat je deze pool wilt verwijderen?' }, :class => 'btn red pool-sign-in'  %>
        </div>

        <div class="grid-r">
          <div class="small-1-3">
            <div class="avatar">
              <%= image_tag @pool.avatar.url(:small), id: 'uploadPreview' %>
              <div class="btn green fileupload">
                <span>Bewerk afbeelding</span>
                <%= f.file_field :avatar, class: "upload", id: "uploadImage", onchange: "PreviewImage();" %>
              </div>
              <script type="text/javascript">
                function PreviewImage() {
                    var oFReader = new FileReader();
                    oFReader.readAsDataURL(document.getElementById("uploadImage").files[0]);

                    oFReader.onload = function (oFREvent) {
                        document.getElementById("uploadPreview").src = oFREvent.target.result;
                    };
                }
              </script>
            </div>
          </div>
          <div class="small-2-3">
            <div class="pool_new_form">
              <% if @pool.errors[:name].empty? %>
                <div class="form-field">
              <% else %>
                <div class="form-field error">
              <% end %>
                <%= f.label :name, 'Pool naam' %>
                <%= f.text_field :name %>
                <span>
                  <% if @pool.errors.any? %>
                    <%= @pool.errors[:name].to_sentence(words_connector: '<br />', two_words_connector: '<br />', last_word_connector: '<br />').html_safe %>
                  <% end %>
                </span>
              </div>

              <div class="form-field">
                <label>Maximaal aantal spelers</label>
                <div class='slider'>
                  <div class='minmax'>
                    <div class='mintext'></div>
                    <%= f.hidden_field :maximum_membership, :class => 'min' %>
                  </div>
                  <div class='rangeslider'></div>
                </div>
              </div>

              <div class="form-field inline">
                <label>Toegankelijkheid</label>
                <% if @pool.is_public || @pool.is_public.nil? %>
                  <%= f.radio_button :is_public, true, :checked => true %>
                  <label for="pool_is_public_true">Openbaar</label>
                  <%= f.radio_button :is_public, false, :checked => false %>
                  <label for="pool_is_public_false">Priv&eacute;</label>
                <% else %>
                  <%= f.radio_button :is_public, true, :checked => false %>
                  <label for="pool_is_public_true">Openbaar</label>
                  <%= f.radio_button :is_public, false, :checked => true %>
                  <label for="pool_is_public_false">Priv&eacute;</label>
                <% end %>
              </div>

              <div class="form-field" id="private_pool_enabled">
                <% if @pool.errors[:password].empty? %>
                  <div class="form-field">
                <% else %>
                  <div class="form-field error">
                <% end %>
                  <%= f.label :password, 'Wachtwoord' %>
                  <%= f.password_field :password %>
                  <span>
                    <% if @pool.errors.any? %>
                      <%= @pool.errors[:password].to_sentence(two_words_connector: '<br />').html_safe %>
                    <% end %>
                  </span>
                </div>

                <% if @pool.errors[:password_confirmation].empty? %>
                  <div class="form-field">
                <% else %>
                  <div class="form-field error">
                <% end %>
                  <%= f.label :password_confirmation, 'Wachtwoord herhalen' %>
                  <%= f.password_field :password_confirmation %>
                  <span>
                    <% if @pool.errors.any? %>
                      <%= @pool.errors[:password_confirmation].to_sentence(two_words_connector: '<br />').html_safe %>
                    <% end %>
                  </span>
                </div>
              </div>

              <div class="form-field">
                <button class="green" type="submit">
                  Wijzigingen opslaan
                </button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class='default-0 medium-1-4'>
    <%= render "shared/aside" %>
    <%= render "shared/aside_admin" %>
    <%= render "shared/aside_ad" %>  
  </div>
</div>
<%= javascript_tag do %>
  poolPassword();
  rangeSlider2(<%= @pool.poolmemberships_count %>, <%= @pool.maximum_membership %>);
<% end %>
<% else %>
Sp&#228;ter!
  <script type="text/javascript">
    window.location.href="/app/"
  </script>
<% end %>

app/views/pools/index.html.erb
<% title "Alle pools" %>
<div class='grid-r'>
  <div class='medium-3-4'>
    <div class='box'>
      <div class='content-header'>
        <h1>Alle pools</h1>
        <div class="form-search">
          <%= form_tag(pools_path, :method => "get", id: "search-form") do %>
            <button class='green'>
              <i class='fa fa-search'></i>
            </button>
            <div>
              <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Zoeken..." %>
            </div>
          <% end %>
        </div>
      </div>
      <div class='pool-help'>
        <p>Om mee te kunnen spelen in een pool dien je deze in de lijst aan te klikken. Wanneer deze niet publiekelijk is, zul je het wachtwoord in moeten voeren. Klik op de groene knop om door te gaan.</p>
      </div>
      <div class='pool-filter'>
        <div class='filter-handle'>
          <h2>Filters</h2>
          <i class='fa fa-caret-right filter-arrow'></i>
        </div>
        <div class='filter-overview'>
          <form action=''>
            <div class='grid-r'>
              <div class='small-1-3 filter-box'>
                <h3>Toegankelijkheid</h3>
                <div class='form-field'>
                  <div class='checkbox'>
                    <% if @openpool == '0' %>
                      <input checked id='fp1' name='openpool' type='radio' value="0">
                    <% else %>
                      <input id='fp1' name='openpool' type='radio' value="0">
                    <% end %>
                    <label for='fp1'>Alle pools</label>
                  </div>
                  <div class='checkbox'>
                    <% if @openpool == '1' %>
                      <input checked id='fp2' name='openpool' type='radio' value="1">
                    <% else %>
                      <input id='fp2' name='openpool' type='radio' value="1">
                    <% end %>
                    <label for='fp2'>Openbare pools</label>
                  </div>
                  <div class='checkbox'>
                    <% if @openpool == '2' %>
                      <input checked id='fp3' name='openpool' type='radio' value="2">
                    <% else %>
                      <input id='fp3' name='openpool' type='radio' value="2">
                    <% end %>
                    <label for='fp3'>Prive pools</label>
                  </div>
                </div>

              </div>
              <div class='small-1-3 filter-box'>
                <h3>Volle pools</h3>
                <div class='form-field'>
                  <div class='checkbox'>
                    <% if @poolspace == '1' %>
                      <input checked id='fvp1' name='poolspace' type='radio' value="1">
                    <% else %>
                      <input id='fvp1' name='poolspace' type='radio' value="1">
                    <% end %>
                    <label for='fvp1'>Tonen</label>
                  </div>
                  <div class='checkbox'>
                    <% if @poolspace == '2' %>
                      <input checked id='fvp2' name='poolspace' type='radio' value="2">
                    <% else %>
                      <input id='fvp2' name='poolspace' type='radio' value="2">
                    <% end %>
                    <label for='fvp2'>Verbergen</label>
                  </div>
                </div>
              </div>
              <div class='small-1-3 filter-box'>
                <h3>Aantal deelnemers</h3>
                <div class='slider'>
                  <div class='minmax'>
                    <div class='mintext'></div>
                    <input class='min' name='playerssearch1' type='hidden' value="<%= @playerssearch1 %>">
                    <div class='maxtext'></div>
                    <input class='max' name='playerssearch2' type='hidden' value="<%= @playerssearch2 %>">
                  </div>
                  <div class='rangeslider'></div>
                </div>
              </div>
            </div>
            <div class='filter-submit'>
              <input class='btn green fullwidth' type='submit' value='Filters toepassen'>
            </div>
          </form>
        </div>
      </div>
      <div class='pool-list'>
        <ul>
          <% @pools.each do |pool| %>
            <li>
              <div class='view-table'>
                <a class='grey pool-list-inner view-row' href='<%= url_for(pool) %>'>
                  <div class='pool-list-img'>
                    <%= image_tag pool.avatar.url(:thumb) %>
                  </div>
                  <div class='pool-list-txt'>
                    <h2><%= pool.name %></h2>
                    <p><%= pool.poolmemberships_count %> / <%= pool.maximum_membership %></p>
                  </div>
                  <div class='pool-list-lock'>
                    <% if pool.is_public? %>
                      <i class='fa fa-unlock unlock'></i>
                    <% else %>
                      <i class='fa fa-lock lock'></i>
                    <% end %>
                  </div>
                </a>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
      <div class='poolpagination'>
        <div class='pages'>
          <div class='view-row'>
            <div class="page-large">
            <%= will_paginate @pools, previous_label: "<i class='fa fa-chevron-left'></i> Vorige", next_label: "Volgende <i class='fa fa-chevron-right'></i>", inner_window: 1, outer_window: 0 %>
            </div>
            <div class="page-small">
            <%= will_paginate @pools, previous_label: "<i class='fa fa-chevron-left'></i> Vorige", next_label: "Volgende <i class='fa fa-chevron-right'></i>", page_links: false %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class='default-0 medium-1-4'>
    <%= render "shared/aside" %>
    <%= render "shared/aside_admin" %>
    <%= render "shared/aside_ad" %>  
  </div>
</div>

<%= javascript_tag do %>
  filterHandle();
  rangeSlider(<%= @playerssearch1 %>,<%= @playerssearch2 %>);
<% end %>

app/views/pools/invite.html.erb
<% title "Vrienden uitnodigen" %>
<div class="grid-r">
  <div class="medium-3-4">
    <div class="box">
      <div class="pool-step">
        <div class="steps">
          <div class="step active">
            1. <span class="default-hide small-show">Pool informatie</span>
          </div>
          <div class="step active">
            2. <span class="default-hide small-show">Bevestigen</span>
          </div>
          <div class="step active">
            3. <span class="default-hide small-show">Vrienden uitnodigen</span>
          </div>
        </div>
      </div>

      <div class="content-header">
        <h1>3. Vrienden uitnodigen</h1>
      </div>

      <div class="pool-invite">
        <p>Door de onderstaande link te kopieren en te versturen, kun je mensen naar jouw zojuist aangemaakte WK pool leiden. Klik eenmaal op de link om deze te selecteren kopieer deze om te delen met al je vrienden!
        </p>
        <div class='form-search'>
          <div>
            <input onclick="this.select();" type="text" value="<%= (request.base_url) + (url_for @pool) %>">
          </div>
        </div>
        </br>
          <%= link_to 'Klik om door te gaan naar jouw pool', pool_path(@pool.id),:class => 'btn green' %>
      </div>
    </div>
  </div>
  <div class='default-0 medium-1-4'>
    <%= render "shared/aside" %>
    <%= render "shared/aside_ad" %>
  </div>
</div>

app/views/pools/pred.html.erb
<div class='grid-r'>
  <div class='medium-3-4'>
    <div class='box'>
      <div class='content-header'>
        <h1>Voorspellingen - <%= @pool.id %></h1>
      </div>
      <div class='pool-list'>
        <ul>
          <li>
              Original score: <br/>
              <% @games.each do |game| %>
                  <tr> 
                    <td><%= Team.find(game.team1_id).name %></td>
                    <td>                  
                      <% if game.score1 == nil && game.score2 == nil %>
                        x - x
                      <% else %>
                        <%= game.score1 %> - <%= game.score2 %>
                      <% end %> 
                    </td>
                    <td><%= Team.find(game.team2_id).name %></td>
                    <td><%= form_for @prediction do |f| %>
                          <%= f.label :prediction1, 'prediction 1' %>
                          <%= f.text_field :prediction1 %>
                          <%= f.label :prediction2, 'prediction 2' %>
                          <%= f.text_field :prediction2 %>
                          <%= hidden_field_tag :game_id, game.id %>
                          <%= hidden_field_tag :poolmembership_id, @poolmembership.id %>
  <!-- 
                          Poolmembership id: <%= debug @poolmembership %>
                          <br/>
                          <br/>
                          Poolmembership <%= Poolmembership.find(current_user.id).id %><br/>
                          User_id <%= Poolmembership.find(current_user.id).user_id %><br/>
                          Pool_id <%= Poolmembership.find(current_user.id).pool_id %><br/>
                          <br/>
                          <br/>

                          Current user id: <%= current_user.id %> <br/>
                          Current pool id: <%= @pool.id %><br/>

                          Current game id: <%= game.id %><br/> -->

                          
                          
                          
                          <br/>
                          <%= f.submit %>
                          <br/>
                    </td>                  
                  </tr></br>
                    <% end %>                             
                <% end %>
                <br/>                
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class='default-0 medium-1-4'>
    <%= render "shared/aside" %>
  </div>
</div>

<%= javascript_tag do %>
  filterHandle();
  rangeSlider();
<% end %>

app/views/pools/show.html.erb
<% title @pool.name %>
<div class='grid-r'>
  <div class='medium-3-4'>


    <div class='box'>
      <div class='content-header'>
        <h1><%= @pool.name %></h1>
      </div>

      <% if current_user %>
        <div class="content-header">
          <span class="default-hide small-show">
            <a href="<%= url_for pools_path %>" class="btn grey left"><i class="fa fa-chevron-left"></i> Terug naar het overzicht</a>
          </span>
          <% if @my_pool %>
            <% if @poolmember.role == 0 %>
              <a href="#pool<%= @pool.id %>" class="btn red pool-sign-in" rel='modal:open'><i class="fa fa-times"></i> Meld je af bij deze pool</a>
            <% else %>
              <a href="<%= @pool.id %>/edit" class="btn green pool-sign-in"><i class="fa fa-cog"></i> Pool aanpassen</a>
            <% end %>
          <% else %>
            <% if @pool.poolmemberships_count == @pool.maximum_membership %>
              <button type="button" class="grey-dark pool-sign-in">Deze pool is vol</button>
            <% else %>
              <a href="#pool<%= @pool.id %>" class="btn green pool-sign-in" rel='modal:open'><i class="fa fa-users"></i> Meld je aan bij deze pool</a>
            <% end %>
          <% end %>
        </div>

        <% else %>
          <div class="content-header ">
             <%= link_to 'Registreren', register_path, :class => 'btn green' %>
          </div>
      <% end %>

      <div class="pooldashboard-content">
        <h2>Stand</h2>

        <table class="table rank">
          <tbody>
            <% @pool.poolmemberships.sort_by(&:score).reverse.each_with_index do |user, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td>
                  <%= link_to User.find(user.user_id).nickname, user_path(user.user_id) %> <% if Poolmembership.find(user.id).role == 1 %>
                  &#9819;
                  <% else %><% end %>
                  <% if User.find(user.user_id) == current_user %>
                  <%= fa_icon 'hand-o-left' %>
                  <% else %><% end %> </td>
              <td class="bold"><%= Poolmembership.find(user.id).score %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class='default-0 medium-1-4'>
    <%= render "shared/aside" %>
    <%= render "shared/aside_admin" %>
    <%= render "shared/aside_ad" %>
  </div>
</div>


<div id='pool<%= @pool.id %>' style='display:none'>
<% if @my_pool %>
  <h1>'<%= @pool.name %>' verlaten?</h1>
  <p>Weet je zeker dat je '<%= @pool.name %>' wilt verlaten?</p>
  <div class='grid-r modal-btns'>
    <div class='default-1 small-1-2'>
      <%= link_to @poolmember, class:'btn green fullwidth', method: :delete do %>
        Ja, ik meld mij af
      <% end %>
    </div>
    <div class='default-1 small-1-2'>
      <button class="btn grey fullwidth" type="button" onclick="$.modal.close();">Nee, ik wil blijven</button>
    </div>
  </div>
<% else %>
  <% if @pool.is_public? %>
    <h1>Bij '<%= @pool.name %>' aansluiten?</h1>
    <p>Weet je zeker dat jij je bij '<%= @pool.name %>' wil aansluiten?</p>
    <%= form_tag poolmemberships_path do %>
      <div class='grid-r modal-btns'>
        <div class='default-1 small-1-2'>
          <%= submit_tag "Ja, ik sluit mij aan", :class => 'btn green fullwidth' %>
          <%= hidden_field_tag :pool_id, @pool.id %>
        </div>
        <div class='default-1 small-1-2'>
          <%= link_to 'Nee, ik wil verder zoeken', pools_path, :class => 'btn grey fullwidth' %>
        </div>
      </div>
    <% end %>
  <% else %>
    <h1>Wachtwoord '<%= @pool.name %>'</h1>
    <p>Bevestig het wachtwoord van '<%= @pool.name %>' om toegang te krijgen.</p>
    <div class='form-search modalpassword'>
      <%= form_tag poolmemberships_path do %>
        <button class='green' type='submit'>
          <i class='fa fa-chevron-right'></i>
        </button>
        <div>
          <%= password_field_tag :password  %>
          <%= hidden_field_tag :pool_id, @pool.id %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>
</div>