config/routes.rb
Wkpool::Application.routes.draw do
  scope '/app' do
    get 'users/welcome' => 'users#welcome', :as => 'welcome'
    get 'pools/:id/invite' => 'pools#invite', :as => 'invite_pool'
    post 'create_multiple_predictions', to: 'predictions#create_multiple_predictions'
    patch 'update_multiple_predictions', to: 'predictions#update_multiple_predictions'
    get 'pouleeindstanden/:id' => 'predictions#pouleeindstanden', :as => 'pouleeindstanden'
    get 'knockoutfase/:id' => 'predictions#knockoutfase', :as => 'knockoutfase'
    get 'bonusvragen/:id' => 'predictions#bonusvragen', :as => 'bonusvragen'
    resources :pools, :users, :predictions, :teampredictions, :poolmemberships, :knockoutpredictions, :quarterpredictions, :semipredictions, :finalpredictions
    post 'create_multiple_predictions', to: 'predictions#create_multiple_predictions'
    get 'givepoints' => 'predictions#givepoints', :as => 'givepoints'
    post 'create_multiple_teampredictions', to: 'teampredictions#create_multiple_teampredictions'
    patch 'update_multiple_teampredictions', to: 'teampredictions#update_multiple_teampredictions'
    get 'givepoints2' => 'predictions#givepoints2', :as => 'givepoints2'
    get 'bier' => 'predictions#bier', :as => 'bier'
    get 'pointsscript' => 'predictions#pointsscript', :as => 'pointsscript'
    get 'pointsscript2' => 'predictions#pointsscript2', :as => 'pointsscript2'
    get 'speluitleg' => 'pages#speluitleg', :as => 'speluitleg'
    get 'ranking' => 'poolmemberships#ranking', :as => 'ranking'
    resources :games do
      member do
        patch :toggle
      end
    end
    resources :teams do
      member do
        patch :toggle
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  get 'logout' => 'sessions#destroy', :as => 'log_out'
  get 'login' => 'sessions#new', :as => 'log_in'
  get 'register' => 'users#new', :as => 'register'

  get 'app' => 'users#dashboard', :as => 'app_root'

  root  'pages#home'

  get 'ping' => proc { |env| [200, {}, ['pong']] }
  get "/500", :to => "errors#error_500"
  get "/404", :to => "errors#error_404"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password validations: false

  has_many :poolmemberships
  has_many :pools, through: :poolmemberships
  has_many :predictions, through: :poolmemberships

  before_validation :downcase_email

  after_create :subscribe, if: :subscribed?

  validates :name,
            length: {
              minimum: 2,
              maximum: 35,
              message: '* Je naam moet tussen de 2 en 35 karakters lang zijn.'
            }

  validates :nickname,
            length: {
              minimum: 2,
              maximum: 35,
              message: '* Je nickname moet tussen de 2 en 35 karakters lang zijn.'
            },
            uniqueness: {
              message: '* Deze alias is al bezet.'
            }

  validates :email,
            uniqueness: {
              message: '* Dit e-mailadres is al in gebruik.'
            },
            format: {
              with: /[a-zA-Z0-9._%-]+@(?:[a-zA-Z0-9-]+\.)+(com|net|org|info|biz|me|edu|gov|nl|se)/,
              message: 'Voer een geldig e-mailadres in.'
            }

  validates :password,
            presence: false,
            allow_blank: false,
            length: {
              minimum: 5,
              message: '* Het wachtwoord moet minimaal 5 karakters zijn.'
            },
            confirmation: {
              message: '* De wachtwoorden komen niet overeen.'
            },
            if: :password

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def subscribe
    mailchimp = Gibbon::API.new
    result = mailchimp.lists.subscribe({
      :id => ENV['MAILCHIMP_LIST_ID'],
      :email => {:email => self.email},
      :double_optin => false,
      :update_existing => true,
      :send_welcome => true
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end

  private

  def downcase_email
    self.email = self.email.downcase if self.email.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :ensure_user, :only => [:create, :new]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @poolmemberships = Poolmembership.where(user_id: @user.id).load
    @games = Game.order(:poule)
    @gamelist = @games.group_by { |t| t.poule }
    @teams = Team.where(:poule => ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']).order(:poule)
    @teamlist = @teams.group_by { |t| t.poule }
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Succesvol geregistreerd en ingelogd.'
      redirect_to welcome_path
    else
      render 'new'
    end
  end

  def dashboard
    @user = User.find(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :password, :password_confirmation, :subscribed, :password_reset_token, :password_reset_sent_at)
  end
end

app/views/users/dashboard.html.erb
<% title "Dashboard" %>
<div class="grid-r">
  <div class="medium-3-4">
   <div class="box">
      <div class="content-header">
        <h1>Dashboard</h1>
      </div>

      <% if current_user.poolmemberships.count < 1 %>
      <div id="contentflash" class="contentflash error">
        <div class="view-table">
          <div class="view-row">
            <div class="flashcontent-icon"><i class="fa fa-users"></i></div>
            <div class="contentflash-text">Let op! Je hebt je nog niet bij een pool aangesloten!</div>
          </div>
        </div>
          <script>contentflashMessage();</script>
      </div>
      <% end %>

      <div id="contentflash" class="contentflash success">
        <div class="view-table">
          <div class="view-row">
            <div class="flashcontent-icon"><i class="fa fa-file-text"></i></div>
            <div class="contentflash-text">De punten voor de poule eindstanden zijn toegewezen!</div>
          </div>
        </div>
          <script>contentflashMessage();</script>
      </div>

      <div class="notifications">
        <div class="notification-header">
          <h2>Meldingen</h2>
        </div>
        <div class='notification-list'>
          <ul>
            <li>
              <div class='view-table'>
                <div class='grey notification-list-inner view-row' href='#modal' rel='modal:open'>
                  <div class='notification-list-icon'>
                   <p> <i class="fa fa-file-text"></i>
                  </div>
                  <div class='notification-list-txt'>
                    <p>mijnwkpool - Administrator <small>- Melding - maandag 16 juni 2014</small></p>
                    <h3>
                      Poule eindstanden.<br/>
                      Omdat het ons is opgevallen dat er veel gebruikers zijn welke de poule eindstanden nog niet hebben ingevuld, en het nog wel mogelijk is om de knock-out fase in te vullen, is er besloten jullie de mogelijkheid te geven om de poule eindstanden nog tot 21.00 uur op dinsdag 17 juni a.s. in te vullen. Na dit moment zal Brazilië namelijk zijn tweede wedstrijd spelen. Er is hiervoor gekozen omdat het niet mogelijk is om de knock-out fase in te vullen zonder de poule eindstanden ingevuld te hebben. Voor de knockoutfase is nog steeds de onderstaande melding van kracht. 
                    </h3>
                  </div>
                </div>
              </div>
            </li>               
            <li>
              <div class='view-table'>
                <div class='grey notification-list-inner view-row' href='#modal' rel='modal:open'>
                  <div class='notification-list-icon'>
                   <p> <i class="fa fa-file-text"></i>
                  </div>
                  <div class='notification-list-txt'>
                    <p>mijnwkpool - Administrator <small>- Melding - donderdag 12 juni 2014</small></p>
                    <h3>
                      Inmiddels is de eerste wedstrijd van het wk begonnen en staan alle voorspellingen van de poule fase vast. Ook de poule eindstanden zijn logischerwijs niet meer aan te passen. Vanaf nu meespelen is alleen nog mogelijk in de knockout fase.<br/> <br/> BELANGRIJK:<br/>  Mensen die al mee spelen, en de knockout fase al ingevuld hebben, moeten dit nog een keer doen. Dit door recente wijzigingen in het systeem. Het beste is om iedere ronde, achtste, kwart, halve en finale na te kijken en op opnieuw in te voeren en op te slaan. Er zijn mogelijk verschuivingen in landen gekomen, hierdoor kunnen je voorspellingen niet meer kloppen. Excuses voor het ongemak. Je hebt hiervoor tot en met 27 juni de tijd (zie spelregels). Vragen en/of opmerkingen: info@mijnwkpool.com of via Facebook.
                    </h3>
                  </div>
                </div>
              </div>
            </li>          
            <li>
              <div class='view-table'>
                <div class='grey notification-list-inner view-row' href='#modal' rel='modal:open'>
                  <div class='notification-list-icon'>
                   <p> <i class="fa fa-file-text"></i>
                  </div>
                  <div class='notification-list-txt'>
                    <p>mijnwkpool - Administrator <small>- Patch notes - dinsdag 10 juni 2014</small></p>
                    <h3>
                      - Voorspellen van poule eindstanden toegevoegd.<br/>                    
                      - Voorspellen van knockout wedstrijden toegevoegd.<br/>
                      - Wachtwoord vergeten optie toegevoegd.<br/>
                      - Responsive design updates.<br/>                      
                      - Bug fixes en verbeteringen door gehele systeem.
                    </h3>
                  </div>
                </div>
              </div>
            </li>          
            <li>
              <div class='view-table'>
                <div class='grey notification-list-inner view-row' href='#modal' rel='modal:open'>
                  <div class='notification-list-icon'>
                   <p> <i class="fa fa-file-text"></i>
                  </div>
                  <div class='notification-list-txt'>
                    <p>mijnwkpool - Administrator <small>- Patch notes - woensdag 28 mei 2014</small></p>
                    <h3>
                      - Voorspellen van poule wedstrijden toegevoegd.<br/>
                      - Pools kunnen aangepast worden door de beheerder.<br/>
                      - Uitslagen van andere gebruikers kunnen worden bekeken.<br/>
                      - Dashboard update.<br/>
                      - Aanmelden voor nieuwsbrief voor nieuwe gebruiker toegevoegd.<br/>
                      - Tekst verbeteringen.<br/>
                      - Bug fixes en verbeteringen door gehele systeem.
                    </h3>
                  </div>
                </div>
              </div>
            </li>

            <li>
              <div class='view-table'>
                <div class='grey notification-list-inner view-row' href='#modal' rel='modal:open'>
                  <div class='notification-list-icon'>
                   <p> <i class="fa fa-file-text"></i>
                  </div>
                  <div class='notification-list-txt'>
                    <p>mijnwkpool - Administrator <small>- Patch notes - woensdag 7 mei 2014</small></p>
                    <h3>
                      - ‘Mijn pools’ toegevoegd aan het mobiele menu.<br/>
                      - Gebruikersnamen linken naar desbetreffende profielen.<br/>
                      - Individuele pools bekijken via pool pop-up in ‘Alle pools’.<br/>
                      - Links geüpdatet.<br/>
                      - E-mailadressen bij inloggen en registreren zijn niet meer hoofdlettergevoelig.<br/>
                      - Tekst updates.<br/>
                      - Overige bug fixes en verbeteringen.
                    </h3>
                  </div>
                </div>
              </div>
            </li>

            <li>
              <div class='view-table'>
                <div class='grey notification-list-inner view-row' href='#modal' rel='modal:open'>
                  <div class='notification-list-icon'>
                   <p> <i class="fa fa-file-text"></i>
                  </div>
                  <div class='notification-list-txt'>
                    <p>mijnwkpool - Administrator</p>
                    <h3>Welkom in je mijnwkpool dashboard, in de toekomst zullen hier meldingen van je pools, vrienden en mijnwkpool verschijnen. Ook zullen hier gegevens komen te staan en kun je jezelf onder andere terugvinden in tussenstanden. Momenteel draait mijnwkpool nog in een testfase. Wanneer je problemen ervaart of suggesties hebt, voel je vrij om dit te melden.</h3>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>

    </div>
  </div>
  <div class='default-0 medium-1-4'>
    <%= render "shared/aside" %>
    <%= render "shared/aside_admin" %>
    <%= render "shared/aside_ad" %> 
  </div>
</div>

app/views/users/index.html.erb
<% title "Gebruikerslijst" %>
<div class='grid-r'>
  <div class='medium-3-4'>
    <div class='box'>
      <div class='content-header'>
        <h1>Gebruikerslijst</h1>
      </div>
      <div class='pool-list'>
        <ul>
          <% @users.each do |user| %>
            <li>
              <div class='view-table'>
                <a class='grey pool-list-inner view-row'>
                  <div class='pool-list-txt'>
                    <%= link_to user.nickname, user_path(user), :class => 'grey pool-list-inner view-row' %>
                  </div>
                </a>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class='default-0 medium-1-4'>
    <%= render "shared/aside" %>
    <%= render "shared/aside_ad" %>   
  </div>
</div>

<%= javascript_tag do %>
  filterHandle();
  rangeSlider();
<% end %>

app/views/users/new.html.erb
<% title "Registreren" %>
<div class="grid-r">
  <div class="default-hide small-1-6 medium-1-4">&nbsp;</div>
  <div class="small-2-3 medium-1-2">
    <div class="box">
      <div class="content-header">
        <h1>Registreren</h1>
      </div>
      <div class="register-form">
        <%= form_for @user do |f| %>
          <% if @user.errors[:name].empty? %>
            <div class="form-field">
          <% else %>
            <div class="form-field error">
          <% end %>
            <%= f.label :name, 'Naam' %>
            <%= f.text_field :name %>
            <span>
            	<% if @user.errors.any? %>
                <%= @user.errors[:name].to_sentence(words_connector: '<br />', two_words_connector: '<br />', last_word_connector: '<br />').html_safe %>
              <% end %>
            </span>
          </div>

          <% if @user.errors[:name].empty? %>
            <div class="form-field">
          <% else %>
            <div class="form-field error">
          <% end %>
            <%= f.label :email, 'E-mail' %>
            <%= f.text_field :email %>
            <span>
            	<% if @user.errors.any? %>
                <%= @user.errors[:email].to_sentence(words_connector: '<br />', two_words_connector: '<br />', last_word_connector: '<br />').html_safe %>
              <% end %>
            </span>
          </div>

          <% if @user.errors[:nickname].empty? %>
            <div class="form-field">
          <% else %>
            <div class="form-field error">
          <% end %>
            <%= f.label :nickname %>
            <%= f.text_field :nickname %>
            <span>
            	<% if @user.errors.any? %>
                <%= @user.errors[:nickname].to_sentence(words_connector: '<br />', two_words_connector: '<br />', last_word_connector: '<br />').html_safe %>
              <% end %>
            </span>
          </div>

          <% if @user.errors[:password].empty? %>
            <div class="form-field">
          <% else %>
            <div class="form-field error">
          <% end %>
            <%= f.label :password, 'Wachtwoord' %>
            <%= f.password_field :password %>
            <span>
            	<% if @user.errors.any? %>
                <%= @user.errors[:password].to_sentence(words_connector: '<br />', two_words_connector: '<br />', last_word_connector: '<br />').html_safe %>
              <% end %>
            </span>
          </div>

          <% if @user.errors[:password_confirmation].empty? %>
            <div class="form-field">
          <% else %>
            <div class="form-field error">
          <% end %>
            <%= f.label :password_confirmation, 'Wachtwoord herhalen' %>
            <%= f.password_field :password_confirmation %>
            <span>
            	<% if @user.errors.any? %>
                <%= @user.errors[:password_confirmation].to_sentence(words_connector: '<br />', two_words_connector: '<br />', last_word_connector: '<br />').html_safe %>
              <% end %>
            </span>
          </div>

          <div class="form-field">
            <label for="#">Aanmelden voor mail bij updates en de mijnwkpool nieuwsbrief?</label>
            <div class="checkbox">
              <%= f.radio_button :subscribed, true, checked: true %>
              <%= f.label :subscribed, 'Ja', value: true %>
            </div>
            <div class="checkbox">
              <%= f.radio_button :subscribed, false, checked: false  %>
              <%= f.label :subscribed, 'Nee', value: false %>
            </div>
          </div>

          <!-- <div class="form-field">
            <p>Door op aanmelden te klikken ga je akkoord met de <a href="#">gebuikersvoorwaarden</a> en het <a href="">privacybeleid</a> van mijnwkpool.</p>
          </div> -->

          <div class="form-field action">
            <div class='default-1 small-1-2'>
              <%= f.submit "Aanmelden", :class => 'btn green fullwidth' %>
            </div>
            <div class='default-1 small-1-2'>
              <%= link_to 'Ik heb al een account', '/login', :class => 'btn grey fullwidth' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="default-hide small-1-6 medium-1-4">&nbsp;</div>
</div>

app/views/users/welcome.html.erb
<% title "Welkom bij mijnwkpool!" %>
<div class="grid-r">
  <div class="default-hide small-1-6 medium-1-4">&nbsp;</div>
  <div class="small-2-3 medium-1-2">
    <div class="box">
      <div class="content-header">
        <h1>Welkom.</h1>
      </div>
      <div class="welcome-box">
        <p>
          Bedankt dat je voor mijnwkpool hebt gekozen! Om nu verder te gaan kun je ervoor kiezen om je bij een pool aan te sluiten, er een aan te maken of om later een keuze te maken.
        </p>
        <div class="form-field action-stacked">
          <div>
            <%= link_to 'Sluit je bij een pool aan', pools_path, :class => 'btn green' %>
          </div>
          <div>
            <%= link_to 'Creeër een pool', new_pool_path, :class => 'btn green' %>
          </div>
          <div>
            <%= link_to 'Zoek later een pool', app_root_path, :class => 'btn grey' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="default-hide small-1-6 medium-1-4">&nbsp;</div>
</div>