config/routes.rb
Wkpool::Application.routes.draw do
  scope '/app' do
    get 'users/welcome' => 'users#welcome', :as => 'welcome'
    get 'pools/:id/invite' => 'pools#invite', :as => 'invite_pool'
    post 'create_multiple_predictions', to: 'predictions#create_multiple_predictions'
    patch 'update_multiple_predictions', to: 'predictions#update_multiple_predictions'
    get 'pouleeindstanden/:id' => 'predictions#pouleeindstanden', :as => 'pouleeindstanden'
    get 'knockoutfase/:id' => 'predictions#knockoutfase', :as => 'knockoutfase'
    get 'bonusvragen/:id' => 'predictions#bonusvragen', :as => 'bonusvragen'
    resources :pools, :users, :predictions, :teampredictions, :poolmemberships, :knockoutpredictions, :quarterpredictions, :semipredictions, :finalpredictions
    post 'create_multiple_predictions', to: 'predictions#create_multiple_predictions'
    get 'givepoints' => 'predictions#givepoints', :as => 'givepoints'
    post 'create_multiple_teampredictions', to: 'teampredictions#create_multiple_teampredictions'
    patch 'update_multiple_teampredictions', to: 'teampredictions#update_multiple_teampredictions'
    get 'givepoints2' => 'predictions#givepoints2', :as => 'givepoints2'
    get 'bier' => 'predictions#bier', :as => 'bier'
    get 'pointsscript' => 'predictions#pointsscript', :as => 'pointsscript'
    get 'pointsscript2' => 'predictions#pointsscript2', :as => 'pointsscript2'
    get 'speluitleg' => 'pages#speluitleg', :as => 'speluitleg'
    get 'ranking' => 'poolmemberships#ranking', :as => 'ranking'
    resources :games do
      member do
        patch :toggle
      end
    end
    resources :teams do
      member do
        patch :toggle
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  get 'logout' => 'sessions#destroy', :as => 'log_out'
  get 'login' => 'sessions#new', :as => 'log_in'
  get 'register' => 'users#new', :as => 'register'

  get 'app' => 'users#dashboard', :as => 'app_root'

  root  'pages#home'

  get 'ping' => proc { |env| [200, {}, ['pong']] }
  get "/500", :to => "errors#error_500"
  get "/404", :to => "errors#error_404"

end

app/views/shared/_aside.html.erb
<% if current_user %>
<div class='box aside'>
  <p>
    <a class="grey no-under" href="https://www.facebook.com/mijnwkpool?fref=photo">
      <i class="fa fa-facebook-square"></i>&nbsp;<small> facebook.com/mijnwkpool</small>
    </a>
  </p>  
  <p>
    <a class="grey no-under" href="https://www.facebook.com/mijnwkpool?fref=photo">
      <i class="fa fa-twitter"></i>&nbsp;<small> twitter.com/mijnwkpool</small>
    </a>
  </p>
  <p>
    <a class="grey no-under" href="https://plus.google.com/+Mijnwkpool/posts">
      <i class="fa fa-google-plus"></i>&nbsp;<small> plus.google.com/+mijnwkpool</small>
    </a>
  </p>  
</div>
<div class='box aside'>
  <div class='side-header'>
    <h2>Mijn pools</h2>
  </div>
  <div class='pool-list-small'>
    <% if current_user.poolmemberships.count > 0 %>
    <ul>
    <% current_user.poolmemberships.each do |pool| %>
      <li>
        <%= link_to pool_path(pool.pool_id),:class => 'grey' do %>
          <%= Pool.find(pool.pool_id).name %>
        <% end %>
      </li>
    <% end %>
    </ul>
    <% else %>
    <br>
    <p>Je zit nog niet in een pool.</p>
    <br>
    <% end %>
    <%= link_to 'Alle pools', pools_path, :class => 'green btn fullwidth'%>
    <br>
    <%= link_to 'Een pool aanmaken', new_pool_path, :class => 'green btn fullwidth'%>
  </div>
</div>
<% else %>

<div class='box aside'>
  <div class='side-header'>
    <h2>Registreer</h2>
  </div>
  <div class='pool-list-small'>
  <br/>
    <p>Om mee te genieten van mijnwkpool en je aan te sluiten bij deze pool, is het vereist om te registreren.</p>
    <br/>
    <%= link_to 'Registreren', register_path, :class => 'green btn fullwidth'%>
    <br>
    <%= link_to 'Ik heb al een account', log_in_path, :class => 'grey btn fullwidth'%>
  </div>
</div>

<% end %>

app/views/shared/_aside_ad.html.erb
<% if current_user %>
<div class='box'>
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- Ad -->
		<ins class="adsbygoogle"
		     style="display:inline-block;width:200px;height:200px"
		     data-ad-client="ca-pub-2751329003398649"
		     data-ad-slot="3877530412"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
</div>
<% end %>

app/views/shared/_aside_admin.html.erb
<% if current_user && current_user.admin == true %>
<div class='box aside'>
  <div class='side-header'>
    <h2>Administrator</h2>
  </div>
  <div class='pool-list-admin'>
    <ul>
      <li>
        <%= link_to 'Ranking', ranking_path, :class => 'grey'%>
      </li>
      <li>
        <%= link_to 'Teams', teams_path, :class => 'grey'%>
      </li>
      <li>
        <%= link_to 'Games', games_path, :class => 'grey'%>
      </li>
      <li>
        <%= link_to 'Punten (poule)', givepoints_path, :class => 'grey'%>
      </li>
      <li>
        <%= link_to 'Punten (eindstanden)', givepoints2_path, :class => 'grey'%>
      </li>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48174666-1', 'mijnwkpool.com');
  ga('send', 'pageview');

</script>

app/views/shared/_login.html.erb
  <% if current_user %>
    Hallo, <%= current_user.nickname %> | ID: <%= current_user.id %> |
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Log in", log_in_path %> | <%= link_to "Register", register_path %>
  <% end %>
  <br/>
  <br/>

app/views/shared/_touch_icon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_url('favicons/apple-touch-icon-57x57.png') %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_url('favicons/apple-touch-icon-114x114.png') %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_url('favicons/apple-touch-icon-72x72.png') %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_url('favicons/apple-touch-icon-144x144.png') %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_url('favicons/apple-touch-icon-60x60.png') %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_url('favicons/apple-touch-icon-120x120.png') %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_url('favicons/apple-touch-icon-76x76.png') %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_url('favicons/apple-touch-icon-152x152.png') %>">
<link rel="icon" type="image/png" href="<%= image_url('favicons/favicon-196x196.png" sizes="196x196') %>">
<link rel="icon" type="image/png" href="<%= image_url('favicons/favicon-160x160.png" sizes="160x160') %>">
<link rel="icon" type="image/png" href="<%= image_url('favicons/favicon-96x96.png" sizes="96x96') %>">
<link rel="icon" type="image/png" href="<%= image_url('favicons/favicon-16x16.png" sizes="16x16') %>">
<link rel="icon" type="image/png" href="<%= image_url('favicons/favicon-32x32.png" sizes="32x32') %>">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<%= image_url('favicons/mstile-144x144.png') %>" >