config/routes.rb
Wkpool::Application.routes.draw do
  scope '/app' do
    get 'users/welcome' => 'users#welcome', :as => 'welcome'
    get 'pools/:id/invite' => 'pools#invite', :as => 'invite_pool'
    post 'create_multiple_predictions', to: 'predictions#create_multiple_predictions'
    patch 'update_multiple_predictions', to: 'predictions#update_multiple_predictions'
    get 'pouleeindstanden/:id' => 'predictions#pouleeindstanden', :as => 'pouleeindstanden'
    get 'knockoutfase/:id' => 'predictions#knockoutfase', :as => 'knockoutfase'
    get 'bonusvragen/:id' => 'predictions#bonusvragen', :as => 'bonusvragen'
    resources :pools, :users, :predictions, :teampredictions, :poolmemberships, :knockoutpredictions, :quarterpredictions, :semipredictions, :finalpredictions
    post 'create_multiple_predictions', to: 'predictions#create_multiple_predictions'
    get 'givepoints' => 'predictions#givepoints', :as => 'givepoints'
    post 'create_multiple_teampredictions', to: 'teampredictions#create_multiple_teampredictions'
    patch 'update_multiple_teampredictions', to: 'teampredictions#update_multiple_teampredictions'
    get 'givepoints2' => 'predictions#givepoints2', :as => 'givepoints2'
    get 'bier' => 'predictions#bier', :as => 'bier'
    get 'pointsscript' => 'predictions#pointsscript', :as => 'pointsscript'
    get 'pointsscript2' => 'predictions#pointsscript2', :as => 'pointsscript2'
    get 'speluitleg' => 'pages#speluitleg', :as => 'speluitleg'
    get 'ranking' => 'poolmemberships#ranking', :as => 'ranking'
    resources :games do
      member do
        patch :toggle
      end
    end
    resources :teams do
      member do
        patch :toggle
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  get 'logout' => 'sessions#destroy', :as => 'log_out'
  get 'login' => 'sessions#new', :as => 'log_in'
  get 'register' => 'users#new', :as => 'register'

  get 'app' => 'users#dashboard', :as => 'app_root'

  root  'pages#home'

  get 'ping' => proc { |env| [200, {}, ['pong']] }
  get "/500", :to => "errors#error_500"
  get "/404", :to => "errors#error_404"

end

app/controllers/knockoutpredictions_controller.rb
class KnockoutpredictionsController < ApplicationController
  before_action :eightteams, :only => [:show, :edit]
  before_action :quarterteams, :only => [:show, :edit]
  before_action :semiteams, :only => [:show]
  before_action :finalteams, :only => [:show]

  before_filter :ensure_admin, :only => [:pointsscript, :pointsscript2, :givepoints, :givepoints2]
  respond_to :html, :json
  def index
    @pool = Pool.find(params[:pool_id])
    @games = Game.all
    @predictions = Prediction.all
  end

  def show
    @pool = Pool.find(params[:id])
    @gameseight = Game.where(gametype: 'Achtste finale').order(date: :asc, time: :asc)
    @gameseightlist = @gameseight.group_by { |t| t.gametype }
    @gamesquarter = Game.where(gametype: 'Kwart finale').order(date: :asc, time: :asc)
    @gamesquarterlist = @gamesquarter.group_by { |t| t.gametype }
    @gamessemi = Game.where(gametype: 'Halve finale').order(date: :asc)
    @gamessemilist = @gamessemi.group_by { |t| t.gametype }
    @gamesfinal = Game.where(gametype: 'Finale').order(date: :asc)
    @gamesfinallist = @gamesfinal.group_by { |t| t.gametype }
  end

  def eightteams
    @pool = Pool.find(params[:id])
    poolmem = Poolmembership.find_by_user_id_and_pool_id(current_user.id, @pool.id).id
    @array = [
      { #1
        team1: {
          pos: 1,
          poule: 'A',
          poolmembership_id: poolmem
        },
        team2: {
          pos: 2,
          poule: 'B',
          poolmembership_id: poolmem
        }
      },
      { #2
        team1: {
          pos: 1,
          poule: 'C',
          poolmembership_id: poolmem
        },
        team2: {
          pos: 2,
          poule: 'D',
          poolmembership_id: poolmem
        }
      },
      { #3
        team1: {
          pos: 1,
          poule: 'B',
          poolmembership_id: poolmem
        },
        team2: {
          pos: 2,
          poule: 'A',
          poolmembership_id: poolmem
        }
      },
      { #4
        team1: {
          pos: 1,
          poule: 'D',
          poolmembership_id: poolmem
        },
        team2: {
          pos: 2,
          poule: 'C',
          poolmembership_id: poolmem
        }
      },
      { #5
        team1: {
          pos: 1,
          poule: 'E',
          poolmembership_id: poolmem
        },
        team2: {
          pos: 2,
          poule: 'F',
          poolmembership_id: poolmem
        }
      },
      { #6
        team1: {
          pos: 1,
          poule: 'G',
          poolmembership_id: poolmem
        },
        team2: {
          pos: 2,
          poule: 'H',
          poolmembership_id: poolmem
        }
      },
      { #7
        team1: {
          pos: 1,
          poule: 'F',
          poolmembership_id: poolmem
        },
        team2: {
          pos: 2,
          poule: 'E',
          poolmembership_id: poolmem
        }
      },
      { #8
        team1: {
          pos: 1,
          poule: 'H',
          poolmembership_id: poolmem
        },
        team2: {
          pos: 2,
          poule: 'G',
          poolmembership_id: poolmem
        }
      }
    ]
  end

  def quarterteams
    @pool = Pool.find(params[:id])
    poolmem = Poolmembership.find_by_user_id_and_pool_id(current_user.id, @pool.id).id
    p1 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 101)
    if p1.present?
      winner1 = p1.winner
    end
    p2 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 102)
    if p2.present?
      winner2 = p2.winner
    end
    p3 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 103)
    if p3.present?
      winner3 = p3.winner
    end
    p4 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 104)
    if p4.present?
      winner4 = p4.winner
    end
    p5 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 105)
    if p5.present?
      winner5 = p5.winner
    end
    p6 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 106)
    if p6.present?
      winner6 = p6.winner
    end
    p7 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 107)
    if p7.present?
      winner7 = p7.winner
    end
    p8 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 108)
    if p8.present?
      winner8 = p8.winner
    end

    @predictionarray = [
      { #1
        team1: {
          game_id: 103,
          final: 4,
          poolmembership_id: poolmem,
          winner: winner3
        },
        team2: {
          game_id: 104,
          final: 4,
          poolmembership_id: poolmem,
          winner: winner4
        }
      },
      { #2
        team1: {
          game_id: 101,
          final: 4,
          poolmembership_id: poolmem,
          winner: winner1
        },
        team2: {
          game_id: 102,
          final: 4,
          poolmembership_id: poolmem,
          winner: winner2
        }
      },
      { #3
        team1: {
          game_id: 107,
          final: 4,
          poolmembership_id: poolmem,
          winner: winner7
        },
        team2: {
          game_id: 108,
          final: 4,
          poolmembership_id: poolmem,
          winner: winner8
        }
      },
      { #4
        team1: {
          game_id: 105,
          final: 4,
          poolmembership_id: poolmem,
          winner: winner5
        },
        team2: {
          game_id: 106,
          final: 4,
          poolmembership_id: poolmem,
          winner: winner6
        }
      }
    ]
  end


  def semiteams
   @pool = Pool.find(params[:id])
    poolmem = Poolmembership.find_by_user_id_and_pool_id(current_user.id, @pool.id).id
    p9 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 109)
    if p9.present?
      winner9 = p9.winner
    end
    p10 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 110)
    if p10.present?
      winner10 = p10.winner
    end
    p11 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 111)
    if p11.present?
      winner11 = p11.winner
    end
    p12 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 112)
    if p12.present?
      winner12 = p12.winner
    end
    @semipredictionarray = [
      { #1
        team1: {
          game_id: 109,
          final: 3,
          poolmembership_id: poolmem,
          winner: winner9
        },
        team2: {
          game_id: 110,
          final: 3,
          poolmembership_id: poolmem,
          winner: winner10
        }
      },
      { #2
        team1: {
          game_id: 111,
          final: 3,
          poolmembership_id: poolmem,
          winner: winner11
        },
        team2: {
          game_id: 112,
          final: 3,
          poolmembership_id: poolmem,
          winner: winner12
        }
      }
    ]
  end

  def finalteams
   @pool = Pool.find(params[:id])
    poolmem = Poolmembership.find_by_user_id_and_pool_id(current_user.id, @pool.id).id
    p1 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 113)
    if p1.present?
      winner1 = p1.winner
    end
    p2 = Prediction.find_by_poolmembership_id_and_game_id(poolmem, 114)
    if p2.present?
      winner2 = p2.winner
    end
    @finalpredictionarray = [
      { #1
        team1: {
          game_id: 113,
          final: 2,
          poolmembership_id: poolmem,
          winner: winner1
        },
        team2: {
          game_id: 114,
          final: 2,
          poolmembership_id: poolmem,
          winner: winner2
        }
      }
    ]
  end

  def create
    @predictions = Prediction.new(prediction_params)
    if @prediction.save
      redirect_to app_root_path
    else
      render 'new'
    end
  end

  def edit
    if Time.now > deadline && Time.now > knockout_deadline
      @pool = Pool.find(params[:id])
      render 'deadline'
    else
      @pool = Pool.find(params[:id])
      @gameseight = Game.where(gametype: 'Achtste finale').order(date: :asc)
      @gameseightlist = @gameseight.group_by { |t| t.gametype }
      @gameseightlist.sort.each_with_index do |(gametype, games), index|
        if @present
          return
        else
          @gameseight.each_with_index do |game, index2|
            current_poolmembership = Poolmembership.find_by_user_id_and_pool_id(current_user.id, @pool.id)
            prediction = Prediction.find_by_poolmembership_id_and_game_id(current_poolmembership, game.id)

            if prediction.present?
              @present = true
            end
          end
        end
      end
      if @present
        render 'edit'
      else
        render 'new'
      end
    end
  end

  private

  def find_poolmembership
    @poolmembership ||= Poolmembership.find(params[:poolmembership_id])
  end

  def knockoutprediction_params
    params.require(:knockoutprediction).permit(:prediction, :id, :score1, :game, :prediction1, :prediction2, :game_id, :poolmembership_id, :pool_id, :team1_id, :team2_id)
  end
end

app/views/knockoutpredictions/edit.html.erb
<% title "Knock-out fase aanpassen - #{@pool.name}" %>
<div class='grid-r'>
  <div class='medium-3-4'>
    <div class='box'>
      <div class="content-header">
        <h1>Mijn voorspellingen</h1>
      </div>
      <div id="contentflash" class="contentflash success">
        <div class="view-table">
          <div class="view-row">
            <div class="contentflash-text-center">Je voorspelt nu voor: <strong><%= @pool.name %></strong></div>
          </div>
        </div>
      </div>

      <div class="prediction-steps">
        <div class="steps">            
          <div class="step active">
            <%= link_to prediction_path(@pool.id) do %>    
              <span class="small-hide">1.</span> <span class="default-hide small-show">Poule wedstrijden</span> 
            <% end %>
          </div>      
          <div class="step active">
            <%= link_to teamprediction_path(@pool.id) do %>          
              <span class="small-hide">2.</span> <span class="default-hide small-show">Poule eindstanden</span>
            <% end %>
          </div>            
          <div class="step active">
            <%= link_to knockoutprediction_path(@pool.id) do %>
              <span class="small-hide">3.</span> <span class="default-hide small-show">Knock-out fase</span>
            <% end %>
          </div>            
          <div class="step">
            <%= link_to bonusvragen_path(@pool.id) do %>          
              <span class="small-hide">4.</span> <span class="default-hide small-show">Bonus vragen</span>
            <% end %>            
          </div>
        </div>
      </div>

      <div class="pooldashboard-content">
        <h2>Achtste finale</h2>
        <%= form_tag controller: :predictions, action: :update_multiple_predictions do %>
          <input name="_method" type="hidden" value="patch" />
          <%= hidden_field_tag 'pool_id', @pool.id %>
          <% @gameseightlist.sort.each_with_index do |(gametype, games), index| %>
            <table class="table poule">
              <thead>
                <tr>
                  <th class="default-hide small-show" colspan="5">&nbsp;</th>
                  <th class="default-hide small-show">&nbsp;</th>
                  <th class="default-hide small-show">&nbsp;</th>
                  <th class="default-hide small-show">Winnaar</th>
                  <th class="default-hide small-show">Uitslag</th>
                  <th>Punten</th>
                </tr>
              </thead>
              <tbody>
               
                <% games.each_with_index do |game, index2| %>
                  <% current_poolmembership = Poolmembership.find_by_user_id_and_pool_id(current_user.id, @pool.id) %>
                  <% prediction = Prediction.find_by_poolmembership_id_and_game_id(current_poolmembership, game.id) %>
                  <% teamfinal1 = @array[index2][:team1] %>
                  <% teamfinal2 = @array[index2][:team2] %>

                  <% teamfinal1 = Team.pouleleader(teamfinal1[:pos], teamfinal1[:poule], teamfinal1[:poolmembership_id]) %>
                  <% if teamfinal1 == nil %>
                    <% team1 = Team.find(game.team1_id) %>                  
                  <% end %>

                  <% teamfinal2 = Team.pouleleader(teamfinal2[:pos], teamfinal2[:poule], teamfinal2[:poolmembership_id]) %>
                  <% if teamfinal2 == nil %>
                    <% team2 = Team.find(game.team2_id) %>
                  <% end %>

                  <%= fields_for "predictions[#{index}#{index2}]", prediction do |p| %>
                    <%= p.hidden_field :poolmembership_id, :value => Poolmembership.find_by_user_id_and_pool_id(current_user.id, @pool.id).id %>
                    <%= p.hidden_field :game_id, :value => game.id %>
                    <%= p.hidden_field :final, :value => 4 %>
                    <%= p.hidden_field :id, :value => prediction.id %>
                    
                    <% if team1.blank? %>                            
                      <%= p.hidden_field :team1_id, :value => teamfinal1[0]['id'] %>
                    <% end %> 
                    <% if team2.blank? %>                                                                   
                      <%= p.hidden_field :team2_id, :value => teamfinal2[0]['id'] %>
                    <% end %> 

                    <tr>
                      <td class="infoshower">
                        <i class="fa fa-question-circle"></i>
                        <div class="infobox hiddeninfo">
                          <% if team1.present? %>                            
                            <%= team1.name %>
                          <% else %>
                            <%= teamfinal1[0]['name'] %>
                          <% end %> 
                          -
                          <% if team2.present? %>   
                            <%= team2.name %>
                          <% else %>
                            <%= teamfinal2[0]['name'] %>
                          <% end %> 
                          <br />
                          <span><%= game.date %>, <%= game.time.strftime('%H:%M') %></span>
                        </div>
                      </td>
                      <td class="default-hide small-show">
                        <% if team1.present? %>                            
                          <%= team1.name %>
                        <% else %>
                          <%= teamfinal1[0]['name'] %>
                        <% end %><br/>
                      </td>
                      <% if team1.present? %>                            
                        <td class="flag" style="background-image: url('<%=team1.avatar.url(:mini)%>')"></td> 
                      <% else %>
                      <% if teamfinal1[0]['id'].to_i < 10 %>
                          <td class="flag" style="background-image: url('/system/teams/avatars/000/000/00<%= teamfinal1[0]['id'] %>/mini/<%= teamfinal1[0]['avatar_file_name']%>')"></td>
                        <% else %>
                          <td class="flag" style="background-image: url('/system/teams/avatars/000/000/0<%= teamfinal1[0]['id'] %>/mini/<%= teamfinal1[0]['avatar_file_name']%>')"></td> 
                        <% end %>  
                      <% end %>     
                      
                      <td class="predict-score">
                        <div class="view-table">
                          <div class="view-row">
                            <div>
                              <%= p.number_field :prediction1, :class => 'predict', :min => 0, :max => 20 %>
                            </div>
                            <div>
                              &ndash;
                            </div>
                            <div>
                              <%= p.number_field :prediction2, :class => 'predict', :min => 0, :max => 20 %>
                            </div>
                          </div>
                        </div>
                      </td>
          
                      <% if team2.present? %>                            
                        <td class="flag" style="background-image: url('<%=team2.avatar.url(:mini)%>')"></td> 
                      <% else %>
                      <% if teamfinal2[0]['id'].to_i < 10 %>
                          <td class="flag" style="background-image: url('/system/teams/avatars/000/000/00<%= teamfinal2[0]['id'] %>/mini/<%= teamfinal2[0]['avatar_file_name']%>')"></td>
                        <% else %>
                          <td class="flag" style="background-image: url('/system/teams/avatars/000/000/0<%= teamfinal2[0]['id'] %>/mini/<%= teamfinal2[0]['avatar_file_name']%>')"></td> 
                        <% end %>  
                      <% end %>     
                      <td class="default-hide small-show"> 
                        <% if team2.present? %>   
                          <%= team2.name %>
                        <% else %>
                          <%= teamfinal2[0]['name'] %>
                        <% end %> <br />
                      </td>
                      <td class="predict-score">
                        <% if team1.present? && team2.present? %>
                          <%= p.select "winner", options_for_select([[team1.name, team1.id], [team2.name, team2.id]], :selected => prediction.winner), { :class => 'dropdown', :style => 'height: 50px; width: 110px; border: 0px;' }%>                     
                        <% elsif team1.present? %>
                          <%= p.select "winner", options_for_select([[team1.name, team1.id], [teamfinal2[0]['name'], teamfinal2[0]['id']]], :selected => prediction.winner), { :class => 'dropdown', :style => 'height: 50px; width: 110px; border: 0px;' }%>                                                              
                        <% elsif team2.present? %>
                          <%= p.select "winner", options_for_select([[teamfinal1[0]['name'], teamfinal1[0]['id']], [team2.name, team2.id]], :selected => prediction.winner), { :class => 'dropdown', :style => 'height: 50px; width: 110px; border: 0px;' }%>                                                    
                        <% else %>                            
                          <%= p.select "winner", options_for_select([[teamfinal1[0]['name'], teamfinal1[0]['id']], [teamfinal2[0]['name'], teamfinal2[0]['id']]], :selected => prediction.winner), { :class => 'dropdown', :style => 'height: 50px; width: 110px; border: 0px;' }%>
                        <% end %>            
                      </td>                          
                      <td class="default-hide small-show">
                        <% if game.score1 == nil && game.score2 == nil %>
                         ? - ?
                        <% else %>
                          <%= game.score1 %> - <%= game.score2 %>
                        <% end %>
                      </td>
                      <td class="bold">
                        <% if prediction.present? && !(game.score1 == nil && game.score2 == nil) %>
                          <%= prediction.pointsearned %>
                        <% else %>
                          x
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          <% end %>
          <div class="content-btn">
            <div class="center">
              <button class="btn green" type="submit">Opslaan</button>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
  <div class='default-0 medium-1-4'>
    <%= render "shared/aside" %>
    <%= render "shared/aside_admin" %>
    <%= render "shared/aside_ad" %>
  </div>
</div>

<script type="text/javascript">
$(".infoshower").hover(function () {
  $(this).find(".hiddeninfo").fadeIn('fast');
}, function () {
  $(this).find(".hiddeninfo").fadeOut('fast');
});
</script>

app/views/knockoutpredictions/index.html.erb
<div class='grid-r'>
  <div class='medium-3-4'>
    <div class='box'>
      <div class='content-header'>
      </div>

      <div class='pool-list'> 
        <ul>
          <li>
            <div class='view-table'>
              <div class='pool-list-txt'>
                <% @games.each do |game| %>            
                  <h3><%= Team.find(game.team1_id).name %>
                  <% if game.score1 == nil && game.score2 == nil %>
                    x - x
                  <% else %>
                    <%= game.score1 %> - <%= game.score2 %>
                  <% end %>
                  <%= Team.find(game.team2_id).name %></h3>
                <% end %><br/>
                
  							<% current_user.predictions.each do |p| %>
                  <% a = Pool.find(params[:pool_id]) %>
                  <% b = Poolmembership.find(p.poolmembership_id) %>

                  <% if a.id == b.pool_id %>
                    Poolmembership ID: <%= best_in_place Prediction.find(p.id), :poolmembership_id %> ||
                    Game ID: <%= best_in_place Prediction.find(p.id), :game_id %> ||
                    <%= best_in_place Prediction.find(p.id), :prediction1 %> -
                    <%= best_in_place Prediction.find(p.id), :prediction2 %><br/>
                  <% else %>
                  <% end %>
                <% end %><br/><br/>
              </div>
            </div>   
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class='default-0 medium-1-4'> 
    <%= render "shared/aside" %>
    <%= render "shared/aside_ad" %>   
  </div>
</div>

       

app/views/knockoutpredictions/update.html.erb
<h1>Knockoutpredictions#update</h1>
<p>Find me in app/views/knockoutpredictions/update.html.erb</p>